apiVersion: v2
name: libro-mind
description: A Helm chart for Libro-Mind E-commerce & AI System
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 15.5.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
