apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: libro-mind
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: libro-mind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/ecom-book-app-2026/libro-mind-repo/backend:v17 # Fix Test Setup (v17)
        imagePullPolicy: IfNotPresent # Changed from Never for cloud
        envFrom:
        - configMapRef:
            name: libro-mind-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: libro-mind-secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /admin/
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /admin/
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          requests:
            memory: "768Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "500m"
