apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: libro-mind
spec:
  type: LoadBalancer # For local testing with minikube
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: libro-mind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/ecom-book-app-2026/libro-mind-repo/frontend:v7 # Public Backend Link (v7)
        imagePullPolicy: IfNotPresent
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://backend-service:8000"
        - name: NEXT_PUBLIC_BACKEND_EXTERNAL_URL
          value: "http://136.113.211.138:8000"
        - name: BACKEND_API_URL
          value: "http://backend-service:8000"
        - name: JSON_SERVER_URL
          value: "http://json-server-service:3002"
        - name: SESSION_SECURE
          value: "false"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "400m"
