# Generated by Django 5.2.9 on 2026-02-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recommendations",
            "0004_alter_book_options_book_created_at_book_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQueryCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=255, unique=True)),
                ("response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
