# Generated by Django 5.2.10 on 2026-02-18 14:44

import django.db.models.deletion
import pgvector.django.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_searchquerycache_alter_book_id_alter_purchase_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('is_positive', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='book',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='book_embedding_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.book'),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['user', 'book'], name='recommendat_user_id_07f2e9_idx'),
        ),
    ]
