apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: libro-mind
spec:
  selector:
    app: backend
  ports:
  - name: http-backend
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: libro-mind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: libro-mind-backend:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: libro-mind-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: libro-mind-secrets
              key: POSTGRES_PASSWORD
        - name: ENABLE_OTEL
          value: "true"
        - name: OTEL_SERVICE_NAME
          value: "django-backend"
        ports:
        - name: http-backend
          containerPort: 8000
        livenessProbe:
          httpGet:
            path: /admin/
            port: http-backend
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 30
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /admin/
            port: http-backend
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 30
          failureThreshold: 10
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1500m"
