apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: your-gcp-project-id # Replace with actual project ID
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager-credentials
            key: service-account-key
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: libro-mind-secrets
  namespace: libro-mind
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: libro-mind-secrets # The k8s secret to create
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: libro-mind-db-password # The name of the secret in GCP Secret Manager
  - secretKey: DJANGO_SECRET_KEY
    remoteRef:
      key: libro-mind-django-secret # The name of the secret in GCP Secret Manager
