apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: libro-mind
spec:
  selector:
    app: ollama
  ports:
  - name: http-ollama
    port: 11434
    targetPort: 11434
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: libro-mind
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      initContainers:
      - name: pull-model
        image: ollama/ollama:latest
        command: ["sh", "-c", "ollama serve & sleep 10 && ollama pull deepseek-r1:1.5b && ollama pull deepseek-coder:1.3b && pkill ollama"]
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - name: http-ollama
          containerPort: 11434
        # Optional: Add volume for model storage to avoid re-downloading
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
            # Uncomment if you have GPU nodes
            # nvidia.com/gpu: 1
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data-pvc
  namespace: libro-mind
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
